export const dummyResponseCompany = {
    status: 'OK',
    request_id: '65b533f5-7fb7-4f1a-9981-d98de14f4470',
    parameters: {
        query: 'gtr investimentos',
        language: 'pt',
        region: 'br',
        lat: -14.235004,
        lng: -51.92528,
        zoom: 13,
        limit: 20,
        offset: 0,
    },
    data: [
        {
            business_id: '0x94dce4238cbc20bf:0x857ca1ebe44bb3c7',
            google_id: '0x94dce4238cbc20bf:0x857ca1ebe44bb3c7',
            place_id: 'ChIJvyC8jCPk3JQRx7NL5OuhfIU',
            google_mid: '/g/11jgt5vj2t',
            phone_number: null,
            name: 'GTR Investimentos',
            latitude: -25.4132279,
            longitude: -49.259176,
            full_address:
                'GTR Investimentos - Av. João Gualberto, 1673 - SALA 91 - Alto da Glória, Curitiba - PR, 80030-001',
            review_count: 0,
            rating: null,
            timezone: 'America/Sao_Paulo',
            working_hours: null,
            website: 'http://gtrinvestimentos.com.br',
            verified: false,
            place_link:
                'https://www.google.com/maps/place/data=!3m1!4b1!4m2!3m1!1s0x94dce4238cbc20bf:0x857ca1ebe44bb3c7',
            cid: '9618740938676089799',
            reviews_link: null,
            owner_id: '101463095472698267504',
            owner_link:
                'https://maps.google.com/maps/contrib/101463095472698267504',
            owner_name: 'GTR Investimentos',
            booking_link: null,
            reservations_link: null,
            business_status: 'OPEN',
            type: 'Serviços de investimentos',
            subtypes: ['Serviços de investimentos'],
            photos_sample: [
                {
                    photo_id: '_-SU6zz8--XvVzkDoTD5gQ',
                    photo_url:
                        'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=_-SU6zz8--XvVzkDoTD5gQ&cb_client=search.gws-prod.gps&w=86&h=86&yaw=323.7926&pitch=0&thumbfov=100',
                    photo_url_large: null,
                    video_thumbnail_url: null,
                    latitude: -25.41337806795686,
                    longitude: -49.25905428639936,
                    type: 'street_view',
                    photo_datetime_utc: '2023-11-26T00:00:00.000Z',
                    photo_timestamp: 1700956800,
                },
            ],
            reviews_per_rating: null,
            photo_count: 1,
            about: {
                summary: null,
                details: {
                    Acessibilidade: {
                        'Entrada com acessibilidade': true,
                        'Estacionamento com acessibilidade': true,
                    },
                },
            },
            address:
                'Av. João Gualberto, 1673 - SALA 91 - Alto da Glória, Curitiba - PR, 80030-001',
            order_link: null,
            price_level: null,
            district: 'Alto da Glória',
            street_address: 'Av. João Gualberto, 1673 - SALA 91',
            city: 'Curitiba',
            zipcode: '80030-001',
            state: 'Paraná',
            country: 'BR',
        },
        {
            business_id: '0x9bda2f63a05a9f:0xa095f82090d5fbfc',
            google_id: '0x9bda2f63a05a9f:0xa095f82090d5fbfc',
            place_id: 'ChIJn1qgYy_amwAR_PvVkCD4laA',
            google_mid: '/g/11fwggqn52',
            phone_number: null,
            name: 'GTR Investimentos',
            latitude: -22.9851158,
            longitude: -43.3586472,
            full_address:
                'GTR Investimentos - Av. João Cabral de Mello Neto, 850 - Bloco 02 SL711 - Barra da Tijuca, Rio de Janeiro - RJ, 22775-057',
            review_count: 0,
            rating: null,
            timezone: 'America/Sao_Paulo',
            working_hours: null,
            website: 'http://gtrinvestimentos.com.br',
            verified: false,
            place_link:
                'https://www.google.com/maps/place/data=!3m1!4b1!4m2!3m1!1s0x9bda2f63a05a9f:0xa095f82090d5fbfc',
            cid: '11571427636350942204',
            reviews_link: null,
            owner_id: '101563848343103716303',
            owner_link:
                'https://maps.google.com/maps/contrib/101563848343103716303',
            owner_name: 'GTR Investimentos',
            booking_link: null,
            reservations_link: null,
            business_status: 'OPEN',
            type: 'Serviços de investimentos',
            subtypes: ['Serviços de investimentos'],
            photos_sample: null,
            reviews_per_rating: null,
            photo_count: 0,
            about: {
                summary: null,
                details: {
                    Acessibilidade: {
                        'Entrada com acessibilidade': true,
                        'Estacionamento com acessibilidade': true,
                    },
                },
            },
            address:
                'Av. João Cabral de Mello Neto, 850 - Bloco 02 SL711 - Barra da Tijuca, Rio de Janeiro - RJ, 22775-057',
            order_link: null,
            price_level: null,
            district: 'Barra da Tijuca',
            street_address:
                'Av. João Cabral de Mello Neto, 850 - Bloco 02 SL711',
            city: 'Rio de Janeiro',
            zipcode: '22775-057',
            state: 'RJ',
            country: 'BR',
        },
    ],
}
